import argparse
import os
import numpy as np


def read_iq_txt(path):
    sample_rate = None
    i_vals = []
    q_vals = []

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith("#"):
                if "sample_rate_hz" in line:
                    parts = line.split(":", 1)
                    if len(parts) == 2:
                        try:
                            sample_rate = float(parts[1].strip())
                        except ValueError:
                            pass
                continue
            parts = line.replace(",", " ").split()
            if len(parts) < 2:
                continue
            i_vals.append(float(parts[0]))
            q_vals.append(float(parts[1]))

    if not i_vals:
        raise ValueError("No IQ samples found in input file")

    i_arr = np.array(i_vals, dtype=np.float32)
    q_arr = np.array(q_vals, dtype=np.float32)
    return i_arr, q_arr, sample_rate


def compute_spectrum(i_arr, q_arr, sample_rate, nfft=None):
    sig = i_arr + 1j * q_arr
    if nfft is None:
        nfft = 1 << (len(sig) - 1).bit_length()

    window = np.hanning(len(sig))
    sig_w = sig * window

    from scipy import fft

    fft_vals = fft.fft(sig_w, n=nfft)
    fft_vals = np.fft.fftshift(fft_vals)
    freqs = np.fft.fftshift(np.fft.fftfreq(nfft, d=1.0 / sample_rate))
    mag = 20 * np.log10(np.maximum(np.abs(fft_vals), 1e-12))
    return freqs, mag


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    default_input = os.path.join(script_dir, "iq_data.txt")

    parser = argparse.ArgumentParser(
        description="Spectrum analysis for BLE IQ waveform using scipy"
    )
    parser.add_argument(
        "input_iq",
        nargs="?",
        default=default_input,
        help="IQ txt file generated by generator",
    )
    parser.add_argument(
        "--sample-rate",
        type=float,
        default=1_000_000,
        help="override sample rate (Hz)",
    )
    parser.add_argument("--nfft", type=int, default=None, help="FFT size")
    parser.add_argument(
        "--spec-nperseg",
        type=int,
        default=1024,
        help="spectrogram segment length",
    )
    parser.add_argument(
        "--spec-noverlap",
        type=int,
        default=512,
        help="spectrogram overlap length",
    )
    parser.add_argument(
        "--chirp-bw",
        type=float,
        default=500e3,
        help="down-chirp bandwidth (Hz)",
    )
    parser.add_argument(
        "--peak-count",
        type=int,
        default=5,
        help="number of peaks to annotate",
    )
    args = parser.parse_args()

    i_arr, q_arr, sr_in_file = read_iq_txt(args.input_iq)
    sample_rate = args.sample_rate if args.sample_rate else sr_in_file

    sig = i_arr + 1j * q_arr
    freqs, mag = compute_spectrum(i_arr, q_arr, sample_rate, nfft=args.nfft)

    t = np.arange(len(sig)) / sample_rate
    duration = t[-1] if len(t) > 0 else 0.0
    if duration <= 0:
        raise ValueError("Signal duration is too short for chirp processing")

    chirp_bw = args.chirp_bw
    f_start = chirp_bw / 2.0
    f_end = -chirp_bw / 2.0
    k = (f_end - f_start) / duration
    phase_chirp = 2 * np.pi * (f_start * t + 0.5 * k * t**2)
    down_chirp = np.exp(-1j * phase_chirp)
    sig_dechirp = sig * down_chirp
    freqs_dc, mag_dc = compute_spectrum(
        sig_dechirp.real, sig_dechirp.imag, sample_rate, nfft=args.nfft
    )

    import matplotlib.pyplot as plt
    phase = np.unwrap(np.angle(sig))
    inst_freq = np.diff(phase) * sample_rate / (2 * np.pi)
    t_inst = np.arange(len(inst_freq)) / sample_rate

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(11, 7))
    ax1.plot(freqs / 1e6, mag, linewidth=1.0, label="Original")
    ax1.set_xlabel("Frequency (MHz)")
    ax1.set_ylabel("Magnitude (dB)")
    ax1.set_title("BLE IQ Spectrum (Original)")
    ax1.grid(True, alpha=0.3)
    ax1.set_xlim(-1.0, 1.0)
    ax1.legend(loc="best")

    ax2.plot(t_inst, inst_freq / 1e6, ".", markersize=1.5)
    ax2.set_xlabel("Time (s)")
    ax2.set_ylabel("Frequency (MHz)")
    ax2.set_title("BLE IQ Instantaneous Frequency")
    ax2.set_ylim(-1.0, 1.0)

    from scipy import signal

    peaks, _ = signal.find_peaks(mag_dc)
    if peaks.size > 0:
        peak_mags = mag_dc[peaks]
        top_idx = np.argsort(peak_mags)[-args.peak_count :]
        top_peaks = peaks[top_idx]
    else:
        top_peaks = np.array([], dtype=int)

    mag_dc_rel = mag_dc - np.max(mag_dc)
    fig2, ax3 = plt.subplots(1, 1, figsize=(11, 4))
    ax3.plot(freqs_dc / 1e6, mag_dc_rel, linewidth=1.0)
    ax3.set_xlabel("Frequency (MHz)")
    ax3.set_ylabel("Relative Magnitude (dB)")
    ax3.set_title("Dechirped FFT (Relative Peaks)")
    ax3.grid(True, alpha=0.3)
    ax3.set_xlim(-1.0, 1.0)
    for idx in top_peaks:
        f_mhz = freqs_dc[idx] / 1e6
        m_db = mag_dc_rel[idx]
        ax3.plot(f_mhz, m_db, "o", markersize=4)
        ax3.annotate(
                f"{f_mhz:.3f} MHz",
                (f_mhz, m_db),
                textcoords="offset points",
                xytext=(4, 6),
                fontsize=8,
            )

    fig3, ax4 = plt.subplots(1, 1, figsize=(11, 4))
    t_sig = np.arange(len(sig)) / sample_rate
    ax4.plot(t_sig, sig.real, linewidth=0.8, label="I")
    ax4.plot(t_sig, sig.imag, linewidth=0.8, label="Q")
    ax4.set_xlabel("Time (s)")
    ax4.set_ylabel("Amplitude")
    ax4.set_title("Time-Domain Waveform")
    ax4.grid(True, alpha=0.3)
    ax4.legend(loc="best")

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
