#!/usr/bin/env python3
"""
Decode BLE packet from ble_waveforms.h using the same logic as
gen_ble_iq.py:simulate_ble_demod().

This is intended for waveforms generated by gen_ble_iq.py where:
- Fs = 30.72 MHz
- symbols are sampled at round(n * SPS), SPS = Fs / 1e6
- tail silence is appended as exact zeros
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import numpy as np


ARRAY_RE = re.compile(
    r"const\s+uint32_t\s+(ble_iq_ch\d+)\s*\[[^\]]*\]\s*[^=]*=\s*\{(.*?)\};",
    re.S,
)
HEX_RE = re.compile(r"0x[0-9A-Fa-f]{1,8}")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Decode BLE packet from ble_waveforms.h")
    p.add_argument("--input", default="ble_waveforms.h")
    p.add_argument("--array", default="ble_iq_ch37")
    p.add_argument("--fs", type=float, default=30.72e6)
    p.add_argument("--sym-rate", type=float, default=1e6)
    p.add_argument("--channel", type=int, default=None, help="Default inferred from array name")
    p.add_argument("--list-arrays", action="store_true")
    return p.parse_args()


def load_arrays(path: Path) -> dict[str, np.ndarray]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    arrays: dict[str, np.ndarray] = {}
    for m in ARRAY_RE.finditer(text):
        name = m.group(1)
        words = HEX_RE.findall(m.group(2))
        if words:
            arrays[name] = np.array([int(w, 16) for w in words], dtype=np.uint32)
    return arrays


def infer_channel(array_name: str, given: int | None) -> int:
    if given is not None:
        return given
    m = re.match(r"ble_iq_ch(\d+)", array_name)
    return int(m.group(1)) if m else 37


def dedup_2t2r(words: np.ndarray) -> np.ndarray:
    if words.size < 2:
        return words
    even = words[0::2]
    odd = words[1::2]
    n = min(len(even), len(odd))
    if n > 0 and float(np.mean(even[:n] == odd[:n])) > 0.95:
        return even
    return words


def words_to_iq_i16(words: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    i_u16 = (words & np.uint32(0xFFFF)).astype(np.uint16)
    q_u16 = ((words >> np.uint32(16)) & np.uint32(0xFFFF)).astype(np.uint16)
    i = i_u16.view(np.int16)
    q = q_u16.view(np.int16)
    iq = i.astype(np.float32) + 1j * q.astype(np.float32)
    return i, q, iq.astype(np.complex64)


def bytes_to_bits_lsb_first(data: bytes) -> np.ndarray:
    out = np.zeros(len(data) * 8, dtype=np.uint8)
    j = 0
    for b in data:
        for k in range(8):
            out[j] = (b >> k) & 1
            j += 1
    return out


def bits_to_bytes_lsb_first(bits: np.ndarray) -> bytes:
    n = (len(bits) // 8) * 8
    bits = bits[:n]
    out = bytearray()
    for i in range(0, n, 8):
        b = 0
        for k in range(8):
            b |= (int(bits[i + k]) & 1) << k
        out.append(b)
    return bytes(out)


def ble_whiten_xor(bits: np.ndarray, channel: int) -> np.ndarray:
    state = 0x40 | (channel & 0x3F)
    out = np.empty_like(bits)
    for i, bit in enumerate(bits):
        out[i] = int(bit) ^ (state & 1)
        new_bit = ((state >> 4) & 1) ^ (state & 1)
        state = (state >> 1) | (new_bit << 6)
    return out


def ble_crc24_reflected(pdu: bytes) -> int:
    crc = 0xAAAAAA
    for b in pdu:
        for i in range(8):
            bit = (b >> i) & 1
            crc_lsb = crc & 1
            crc >>= 1
            if bit ^ crc_lsb:
                crc ^= 0xDA6000
    return crc & 0xFFFFFF


def main() -> int:
    args = parse_args()
    path = Path(args.input)
    if not path.exists():
        print(f"ERROR: not found: {path}", file=sys.stderr)
        return 1

    arrays = load_arrays(path)
    if not arrays:
        print("ERROR: no arrays found", file=sys.stderr)
        return 1

    if args.list_arrays:
        for name in sorted(arrays):
            print(name)
        return 0

    if args.array not in arrays:
        print(f"ERROR: array not found: {args.array}", file=sys.stderr)
        return 1

    channel = infer_channel(args.array, args.channel)
    words = dedup_2t2r(arrays[args.array])
    i, q, iq = words_to_iq_i16(words)

    active_idx = np.where((i != 0) | (q != 0))[0]
    if active_idx.size == 0:
        print("ERROR: waveform contains only zeros", file=sys.stderr)
        return 1
    active_len = int(active_idx[-1] + 1)
    iq_active = iq[:active_len]

    sps = args.fs / args.sym_rate
    bits_len = int(round(active_len / sps))
    if bits_len < 40:
        print("ERROR: active packet too short", file=sys.stderr)
        return 1

    phase = np.unwrap(np.angle(iq_active))
    freq_dev = np.diff(phase) * args.fs / (2 * np.pi)

    sample_indices = np.round(np.arange(bits_len) * sps).astype(np.int64)
    sample_indices = sample_indices[sample_indices < len(freq_dev)]
    bits = (freq_dev[sample_indices] > 0).astype(np.uint8)

    if len(bits) < 40:
        print("ERROR: demodulated bits too short", file=sys.stderr)
        return 1

    preamble = bits_to_bytes_lsb_first(bits[:8])
    access_addr = bits_to_bytes_lsb_first(bits[8:40])

    whitened_payload_bits = bits[40:]
    payload_bits = ble_whiten_xor(whitened_payload_bits, channel)
    payload_bytes = bits_to_bytes_lsb_first(payload_bits)

    if len(payload_bytes) < 2:
        print("ERROR: payload decode failed", file=sys.stderr)
        return 1

    pdu_len = payload_bytes[1] & 0x3F
    need = 2 + pdu_len + 3
    if len(payload_bytes) < need:
        print(f"ERROR: not enough bytes, need {need}, got {len(payload_bytes)}", file=sys.stderr)
        return 1

    pdu_crc = payload_bytes[:need]
    pdu = payload_bytes[: 2 + pdu_len]
    crc_rx_b = payload_bytes[2 + pdu_len : 2 + pdu_len + 3]
    crc_rx = crc_rx_b[0] | (crc_rx_b[1] << 8) | (crc_rx_b[2] << 16)
    crc_calc = ble_crc24_reflected(pdu)

    full_packet = preamble + access_addr + pdu_crc

    print("Decoded BLE Packet")
    print(f"array          : {args.array}")
    print(f"channel        : {channel}")
    print(f"active_samples : {active_len}")
    print(f"decoded_bits   : {len(bits)}")
    print(f"preamble       : {preamble.hex().upper()}")
    print(f"access_address : {access_addr.hex().upper()}")
    print(f"pdu_plus_crc   : {pdu_crc.hex().upper()}")
    print(f"full_packet    : {full_packet.hex().upper()}")
    print(f"crc_rx         : {crc_rx:06X}")
    print(f"crc_calc       : {crc_calc:06X}")
    print(f"crc_ok         : {crc_rx == crc_calc}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
